# Cross-compile macOS x86_64 targets from Linux via osxcross (setup-osxcross action).
set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

if(DEFINED ENV{OSXCROSS_TARGET})
    set(BV2_OSXCROSS_ROOT "$ENV{OSXCROSS_TARGET}")
else()
    message(FATAL_ERROR "OSXCROSS_TARGET is not set (run mbround18/setup-osxcross first)")
endif()

if(NOT DEFINED OSXCross_SDK_VERSION)
    set(OSXCross_SDK_VERSION "12.3" CACHE STRING "MacOSX SDK version matching setup-osxcross osx-version")
endif()

set(BV2_OSX_SYSROOT "${BV2_OSXCROSS_ROOT}/SDK/MacOSX${OSXCross_SDK_VERSION}.sdk")
if(NOT EXISTS "${BV2_OSX_SYSROOT}")
    file(GLOB BV2_OSX_SYSROOT_CANDIDATES "${BV2_OSXCROSS_ROOT}/SDK/MacOSX*.sdk")
    list(LENGTH BV2_OSX_SYSROOT_CANDIDATES BV2_OSX_SYSROOT_COUNT)
    if(BV2_OSX_SYSROOT_COUNT GREATER 0)
        list(GET BV2_OSX_SYSROOT_CANDIDATES 0 BV2_OSX_SYSROOT)
    else()
        message(FATAL_ERROR "No MacOSX SDK under ${BV2_OSXCROSS_ROOT}/SDK")
    endif()
endif()

set(CMAKE_OSX_SYSROOT "${BV2_OSX_SYSROOT}" CACHE PATH "osxcross SDK sysroot" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET "10.13" CACHE STRING "" FORCE)
set(CMAKE_OSX_ARCHITECTURES "x86_64" CACHE STRING "" FORCE)

find_program(BV2_OSXCROSS_CC NAMES o64-clang x86_64-apple-darwin-clang
    PATHS "${BV2_OSXCROSS_ROOT}/bin" ENV PATH)
find_program(BV2_OSXCROSS_CXX NAMES o64-clang++ x86_64-apple-darwin-clang++
    PATHS "${BV2_OSXCROSS_ROOT}/bin" ENV PATH)

if(NOT BV2_OSXCROSS_CC OR NOT BV2_OSXCROSS_CXX)
    message(FATAL_ERROR "osxcross clang not found under ${BV2_OSXCROSS_ROOT}/bin")
endif()

set(CMAKE_C_COMPILER "${BV2_OSXCROSS_CC}")
set(CMAKE_CXX_COMPILER "${BV2_OSXCROSS_CXX}")

set(CMAKE_FIND_ROOT_PATH "${CMAKE_OSX_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
